name: Nuggetz Push
on:
  push:
    branches:
      - '*'
      - '!site'
jobs:
  Build-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo "Nuggetz build on `push` started"
      - run: echo "building on branch ${{ github.ref }}"
      - run: echo "💡 The ${{ github.ref }} of ${{ github.repository }} repository has been cloned to the runner"
      - run: cp ./src/. ./public/.
      - name: Commit build to 'site' branch
        uses: EndBug/add-and-commit@v7
        with:
          add: 'public'
          branch: 'site'
          message: 'Nuggetz build commit'
      - run: echo "Build status is ${{ job.status }}"