on:
  schedule:
    - cron:  '10,40 7-20 * * *'
jobs:
  Update-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Running build
        run: cp ./src/* ./public

      - name: Push to `site` branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: site
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Nuggetz build on `update`"

      - name: Build completed
        run: echo "Build status is ${{ job.status }}"