name: Nuggetz Update
on:
  schedule:
    - cron:  '30 7-20 * * *'
  workflow_dispatch:
jobs:
  Update-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Running build using Nuggetz docker image
        run: docker run -v ${{ github.workspace }}/src:/app/src -v ${{ github.workspace }}/data:/app/data --name nuggetz slippytrumpet/nuggetz:v0.0.1

      - name: Copying artifacts from container
        run: docker cp nuggetz:/app/public/. ./public

      - name: Pushing to `site` branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: site
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Nuggetz build on `update`"

      - name: Build completed
        run: echo "Build status is ${{ job.status }}"